# Generated by Django 4.2.7 on 2023-12-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_user_alter_message_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('message', models.ManyToManyField(blank=True, db_index=True, to='app.message')),
            ],
        ),
    ]
