# Generated by Django 4.2.7 on 2023-12-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_basemodels_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodels',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
