# Generated by Django 4.2.7 on 2024-01-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('channel', models.CharField(blank=True, max_length=1000, null=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True)),
                ('user_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_error_occurred', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('n_generated_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('n_context_token', models.CharField(blank=True, max_length=1000, null=True)),
                ('model', models.CharField(blank=True, max_length=1000, null=True)),
                ('cost', models.CharField(blank=True, max_length=1000, null=True)),
                ('complete_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
