# Generated by Django 4.2.7 on 2024-01-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Logs'},
        ),
    ]
