# Generated by Django 4.2.9 on 2024-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_log_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=40, null=True),
        ),
    ]
