# Generated by Django 4.2.7 on 2024-01-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_log_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=40, null=True),
        ),
    ]
